export const templates = [
  {
    name: 'Minimalist',
    // description: 'A clean and simple template focusing on the essentials. Perfect for getting started or for those who prefer a straightforward layout.',
    data: {
      name: 'Abhijeet Bhale',
      tagline: 'A passionate frontend developer from India',
      description: 'I am a self-taught frontend developer with a passion for creating beautiful and functional web applications. I am always looking for new challenges and opportunities to learn and grow as a developer.',
      work: [
        { projectName: 'Readme Generator', projectLink: 'https://github.com/abhijeetBhale/Readme-Generator' },
        { projectName: '', projectLink: '' },
        { projectName: '', projectLink: '' },
        { info: 'React, Vite, and Tailwind CSS' },
        { info: '' },
        { info: 'Open to new opportunities' },
        { info: 'Coffee enthusiast' },
      ],
      skills: {
        'Languages': ['JavaScript', 'Python', 'HTML5', 'CSS3'],
        'Frontend': ['React', 'Vite', 'Tailwind CSS', 'Bootstrap'],
      },
      socials: {
        github: 'abhijeetBhale',
        linkedin: 'in/abhijeet-bhale-5b1b3b1b3/',
      },
      analytics: {
        showStatsCard: true,
        showLanguages: true,
        showContributions: false,
        showProfileViews: true,
        showStreakStats: false,
        showTrophies: false,
        showSummaryCards: false,
        showTechQuote: false,
      },
      githubTheme: 'radical',
      typingSvg: {
        lines: [
          'Welcome!',
          'Frontend Dev',
          'React Expert',
          'Always learning.',
          'Let\'s connect!',
        ],
        font: 'Fira Code',
        color: '07EEF2',
        size: 24,
        repeat: true,
      },
    },
  },
  {
    name: 'Comprehensive',
    // description: 'A detailed template that includes sections for work, skills, analytics, and social media. Ideal for showcasing a wide range of your professional life.',
    data: {
      name: 'Jane Doe',
      tagline: 'Full-Stack Developer | Open-Source Contributor',
      description: 'I am a full-stack developer with over 5 years of experience in building scalable and efficient web applications. I have a strong background in both frontend and backend technologies, and I am passionate about creating seamless user experiences. I am a firm believer in the power of open-source and I actively contribute to various projects.',
      work: [
        { projectName: 'Project A', projectLink: 'https://github.com/janedoe/project-a' },
        { projectName: 'Project B', projectLink: 'https://github.com/janedoe/project-b' },
        { projectName: 'Project C', projectLink: 'https://github.com/janedoe/project-c' },
        { info: 'Node.js, Express, MongoDB' },
        { info: 'Open to collaborating on open-source projects.' },
        { info: 'Feel free to reach out to me for any inquiries.' },
        { info: 'I enjoy hiking and photography in my free time.' },
      ],
      skills: {
        'Languages': ['JavaScript', 'TypeScript', 'Python', 'Go'],
        'Frontend': ['React', 'Next.js', 'Tailwind CSS', 'Sass'],
        'Backend': ['Node.js', 'Express', 'Django', 'Flask'],
        'Database': ['MongoDB', 'PostgreSQL', 'MySQL', 'Redis'],
        'DevOps': ['Docker', 'Kubernetes', 'AWS', 'GCP'],
      },
      socials: {
        github: 'janedoe',
        twitter: 'janedoe',
        linkedin: 'in/janedoe',
        devto: 'janedoe',
      },
      analytics: {
        showStatsCard: true,
        showLanguages: true,
        showContributions: true,
        showProfileViews: true,
        showStreakStats: true,
        showTrophies: true,
        showSummaryCards: true,
        showTechQuote: true,
      },
      githubTheme: 'dracula',
      typingSvg: {
        lines: [
          'Full-Stack Dev',
          'Building scalable apps',
          'Efficient applications',
          'Open to collaboration',
          'Let\'s build together!',
        ],
        font: 'Fira Code',
        color: '8A2BE2',
        size: 22,
        repeat: true,
      },
    },
  },
  {
    name: 'Tech Enthusiast',
    // description: 'A template for those who love to showcase their technical skills and projects. Includes a wide variety of skill sections and project details.',
    data: {
      name: 'Alex Smith',
      tagline: 'Software Engineer | AI & Machine Learning Enthusiast',
      description: 'I am a software engineer with a keen interest in artificial intelligence and machine learning. I have experience in developing and deploying machine learning models for various applications, including natural language processing and computer vision. I am always excited to learn about new advancements in the field and apply them to solve real-world problems.',
      work: [
        { projectName: 'AI Chatbot', projectLink: '' },
        { projectName: 'Image Recognition API', projectLink: '' },
        { projectName: 'Data Visualization Dashboard', projectLink: '' },
        { info: 'Python, TensorFlow, PyTorch, Scikit-learn' },
        { info: 'Looking for research collaborations in AI/ML.' },
        { info: 'Ask me about deep learning and neural networks.' },
        { info: 'I am also a huge fan of sci-fi movies.' },
      ],
      skills: {
        'AI/ML': ['TensorFlow', 'PyTorch', 'Keras', 'Scikit-learn', 'OpenCV', 'Pandas', 'NumPy'],
        'Languages': ['Python', 'C++', 'Java'],
        'Backend': ['Django', 'Flask', 'FastAPI'],
        'Database': ['MongoDB', 'PostgreSQL'],
        'DevOps': ['Docker', 'Git'],
      },
      socials: {
        github: 'alexsmith',
        linkedin: 'in/alexsmith',
        stackoverflow: 'users/123456/alexsmith',
      },
      analytics: {
        showStatsCard: true,
        showLanguages: true,
        showContributions: true,
        showProfileViews: true,
        showStreakStats: false,
        showTrophies: true,
        showSummaryCards: false,
        showTechQuote: true,
      },
      githubTheme: 'tokyonight',
      typingSvg: {
        lines: [
          'Software Engineer',
          'AI/ML Specialist',
          'Building the future',
          'One algorithm at a time',
          'Let\'s create!',
        ],
        font: 'JetBrains Mono',
        color: '32CD32',
        size: 24,
        repeat: true,
      },
    },
  },
  {
    name: 'Creative Coder',
    // description: 'A visually appealing template for creative coders and designers. Highlights visual projects and design skills with a stylish and modern layout.',
    data: {
      name: 'Emily White',
      tagline: 'Creative Developer | UI/UX Designer',
      description: 'I am a creative developer and UI/UX designer with a passion for crafting engaging and immersive digital experiences. I specialize in combining my skills in design and development to create unique and innovative projects. I am constantly exploring new ways to use technology to tell stories and evoke emotions.',
      work: [
        { projectName: 'Interactive Art Installation', projectLink: '' },
        { projectName: 'Generative Art Gallery', projectLink: '' },
        { projectName: 'UI/UX Case Study for a Mobile App', projectLink: '' },
        { info: 'JavaScript, p5.js, Three.js, Figma' },
        { info: 'Looking for collaborations on creative coding projects.' },
        { info: 'Ask me about generative art and creative coding.' },
        { info: 'I am also a passionate painter and musician.' },
      ],
      skills: {
        'Creative Coding': ['p5.js', 'Processing', 'Three.js', 'GLSL'],
        'Frontend': ['React', 'Vue.js', 'Svelte', 'GSAP'],
        'Design': ['Figma', 'Sketch', 'Adobe XD', 'Photoshop', 'Illustrator'],
      },
      socials: {
        github: 'emilywhite',
        codepen: 'emilywhite',
        dribbble: 'emilywhite',
        behance: 'emilywhite',
        instagram: 'emilywhite.art',
      },
      analytics: {
        showStatsCard: false,
        showLanguages: true,
        showContributions: false,
        showProfileViews: true,
        showStreakStats: false,
        showTrophies: false,
        showSummaryCards: false,
        showTechQuote: true,
      },
      githubTheme: 'merko',
      typingSvg: {
        lines: [
          'Creative Developer',
          'UI/UX Designer',
          'Art meets code',
          'Making the web beautiful',
          'Let\'s get creative!',
        ],
        font: 'Pacifico',
        color: 'FF69B4',
        size: 26,
        repeat: true,
      },
    },
  },
];